#!/bin/bash

#colors
RED='\[\033[1;31m\]'
YELLOW='\[\033[33;1m\]'
BLUE='\[\033[01;34m\]'
WHITE='\[\033[0;37m\]'
DASH='\342\224\200'
CYAN='\[\033[1;36m\]'
PURPLE='\[\033[1;35m\]'
GREEN='\[\033[1;32m\]'
function git_branch(){

	local BRANCH=$(git branch 2>/dev/null| grep "*" | awk '{print $2}')
	if [ ! "$BRANCH" == "" ]
	then		
		echo -e "$(git_color)( $BRANCH)"
	else
		echo ""
	fi		
}
function git_color(){
	untracked=$(git status | grep -i "untracked\|new file")
	modified=$(git status | grep -i "modified")

		if [ ! "$untracked" == "" ]
		then
			echo -e "\033[1;31m"
		elif [ ! "$modified" == "" ]
		then
			echo -e "\033[1;33m"
		else
			echo -e "\033[1;32m"
		fi
}





#PS1="${RED}┌───=[ ${YELLOW} \u${RED} ]$DASH[ ${CYAN} \w${RED} ]${RED}\$("git_color")\$("git_branch")$DASH[ ${BLUE}\@${RED} ]\n${RED}└──▶ ${GREEN}"

PS1="${YELLOW}╭─╼${CYAN} \w \$("git_branch")\n${YELLOW}╰──▶ ${GREEN}"

alias pacman="sudo pacman"
alias upd="sudo pacman -Syu -y"
alias clip='xclip -selection clipboard'
