# Variables
$mainMod = SUPER
$primaryMonitor = eDP-1
$secondaryMonitor = HDMI-A-1
$touchpad = synaptics-tm3096-001
$terminal = alacritty

# Monitors
monitor=,preferred,auto,1,mirror,$primaryMonitor

# Environment
env = XCURSOR_SIZE,18
env = WLR_NO_HARDWARE_CURSORS,1
env = GTK_THEME,Graphite-Dark
env = QT_QPA_PLATFORM,wayland;xcb
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# General
general {
    gaps_in = 3
    gaps_out = 3
    border_size = 2
    col.active_border = rgba(e5e5e5ee)
    col.inactive_border = rgba(595959aa)
    layout = dwindle
    allow_tearing = false
    resize_on_border = true
}

# Misc
misc {
    force_default_wallpaper = 0
    vrr = 0
}