input {
    kb_layout = us
    follow_mouse = 1
    numlock_by_default = true
    sensitivity = -0.6

    touchpad {
        natural_scroll = yes 
    }
}

device {
    name = $touchpad
    sensitivity = -0.2
}

gestures {
    workspace_swipe_min_speed_to_force = 5
}

gesture = 3, horizontal, workspace