exec = egrep -q open /proc/acpi/button/lid/LID0/state || (hyprctl dispatch dpms off && sleep 0.5 && hyprlock && sleep 1 && systemctl suspend)

exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = ~/dotfiles/hypr/scripts/xdg.sh

exec-once = mako
exec-once = ~/.config/waybar/scripts/launch.sh
exec-once = udiskie 

exec-once = hyprpaper
exec-once = hypridle

exec-once = wlsunset -S 07:00 -s 18:00
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = gsettings set org.gnome.desktop.interface cursor-theme Adwaita
exec-once = nm-applet

exec-once = alacritty --class term-special
exec-once = hyprctl dispatch workspace 1