animations {
    enabled = true
    bezier = wind, 0.05, 0.9, 0.1, 1.0
    bezier = winIn, 0.1, 1.1, 0.1, 1.02
    bezier = winOut, 0.3, 0.3, 0, 1
    bezier = liner, 1, 1, 1, 1

    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide

    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop
    animation = fade, 1, 1, default
    animation = workspaces, 1, 5, wind
}

decoration {
    rounding = 8
    blur {
        enabled = true
        size = 20
        passes = 2
        new_optimizations = on
        xray = true
    }
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_status = master
}