# Workspaces
workspace=1,monitor:$primaryMonitor
workspace=2,monitor:$secondaryMonitor
workspace=3,monitor:$primaryMonitor
workspace=4,monitor:$secondaryMonitor
workspace=5,monitor:$primaryMonitor
workspace=6,monitor:$secondaryMonitor
workspace=7,monitor:$primaryMonitor
workspace=8,monitor:$secondaryMonitor
workspace=9,monitor:$primaryMonitor
workspace=10,monitor:$secondaryMonitor

# Window rules
#---------Window Rules----------#

windowrule {
  name = windowrule-1
  float = on
  match:class = (org.pulseaudio.pavucontrol)$
}

windowrule {
  name = windowrule-2
  no_blur = on
  match:class = ^()$
  match:title = ^()$
}

windowrule {
  name = windowrule-3
  no_focus = on
  match:title = ^(win[0-9]+)$
}

#------Workspace binding-------#
windowrule {
  name = windowrule-4
  workspace = 2
  match:class = ^(firefox)$
}

windowrule {
  name = windowrule-5
  workspace = 2
  match:class = ^(google-chrome)$
}

windowrule {
  name = windowrule-6
  workspace = 3
  match:class = ^(sublime_text)$
}

windowrule {
  name = windowrule-7
  workspace = 3
  match:class = ^(code-oss)$
}

windowrule {
  name = windowrule-8
  workspace = 10
  match:class = ^(discord)$
}

windowrule {
  name = windowrule-9
  workspace = 9
  match:class = ^(obsidian)$
}

windowrule {
  name = windowrule-10
  workspace = 1
  match:class = ^(org.gnome.Nautilus)$
}

windowrule {
  name = windowrule-11
  match:class = ^(Alacritty)$
  workspace = 1
}

windowrule {
  name = windowrule-special
  match:class = ^(term-special)$
  workspace = special
  float  = on
  size = 800 350
}

windowrule {
  name = windowrule-12
  float = on
  workspace = current
  match:class = ^(xdg-desktop-portal-gtk)$
}

windowrule {
  name = windowrule-13
  workspace = current
  match:title = (Save As|Open File|Messenger call - Google Chrome)
  float = on
}

windowrule {
  name = windowrule-14
  pin = on
  size = 600 400
  match:class = wofi
}